### ISSUE TITLE
Binning fails on Microsoft Windows

### ISSUE THREAD

**Issue by KeironO** [KeironO/DIMEpy#3]
**Platform:** Microsoft Windows 10 (x64 bit)
**Code to reproduce:**

```python
import dimepy
import matplotlib.pyplot as plt

sl = dimepy.SpectrumList()

s0 = dimepy.Spectrum("E:\Data\Mixes\mzml\Mix1a.mzML", polarity="positive", snr_estimator="mean")
s0.baseline_correction(qtl=0.6)
sl.append(s0)
s1 = dimepy.Spectrum("E:\Data\Mixes\mzml\Mix2a.mzML", polarity="positive", snr_estimator="mean")
s1.baseline_correction(qtl=0.6)
sl.append(s1)

slp = dimepy.SpectrumListProcessor(sl)

slp.binning(n_jobs=2)
```
**Description:** I am unable to perform multiprocessed binning on a Microsoft Windows VM.

**Stacktrace:**

```
(dimepy-dev) C:\Users\keiron\Documents>python test.py
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    slp.binning(n_jobs=2)
  File "C:\Users\keiron\vens\dimepy-dev\lib\site-packages\dimepy\SpectrumListProcessor.py", line 134, in binning
    _bin, [spectrum for spectrum in self.to_list()]).get()
  File "C:\Users\keiron\vens\dimepy-dev\lib\site-packages\multiprocess\pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

**Comment by KeironO** [comment]
Fixed: https://github.com/KeironO/DIMEpy/pull/6
